# Generated by Django 2.2 on 2023-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20230619_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_price',
            field=models.IntegerField(default=0),
        ),
    ]
