# Generated by Django 2.2 on 2023-06-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20230620_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '浏览商品分类表', 'verbose_name_plural': '商品分类管理'},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '浏览商品表', 'verbose_name_plural': '商品信息管理'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_css',
            field=models.CharField(max_length=20, verbose_name='分类样式'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_img',
            field=models.ImageField(upload_to='cag', verbose_name='分类图片'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_name',
            field=models.CharField(max_length=30, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_cag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='所属的分类'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_desc',
            field=models.CharField(max_length=1000, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.ImageField(upload_to='goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_name',
            field=models.CharField(max_length=100, verbose_name='商品名字'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='商品价格'),
        ),
        migrations.AlterModelTable(
            name='goodscategory',
            table='goods_goodscategory',
        ),
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goods_goodsinfo',
        ),
    ]
