# Generated by Django 2.2 on 2023-06-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230619_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_fee',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
    ]
