# Generated by Django 2.2 on 2023-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20230619_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_fee',
            field=models.IntegerField(default=10),
        ),
    ]
