# Generated by Django 2.2 on 2023-06-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20230620_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '浏览订单商品表', 'verbose_name_plural': '订单商品管理'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '浏览订单信息表', 'verbose_name_plural': '订单信息管理'},
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='所属商品'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_num',
            field=models.IntegerField(verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderInfo', verbose_name='商品所属订单'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_addr',
            field=models.CharField(max_length=100, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_extra',
            field=models.CharField(max_length=200, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_fee',
            field=models.IntegerField(default=10, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(max_length=100, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_recv',
            field=models.CharField(max_length=50, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(1, '代付款'), (2, '代付款'), (3, '代付款'), (4, '代付款')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_tele',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterModelTable(
            name='ordergoods',
            table='cart_ordergoods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='cart_orderinfo',
        ),
    ]
